### ISSUE TITLE
Issue with Version identification and 'pip install'

### ISSUE THREAD

**Issue by thomasfillon** [DavidDoukhan/py_sonicvisualiser#2]
Hi David !

There is an issue when installing  _py-sonicvisualiser_ with `pip install` from Pypi.
Pip was not able to find a version that satisfies the requirement appearently because _py-sonicvisualiser_ current version is is **0.2-9-gebe83bd** and such a naming convention seems not to be supported by Pip (see http://stackoverflow.com/a/18319230) which seems to consider releases as pre-releases.

The workaround for setting _py-sonicvisualiser_ as a requirement is to specify the exact version: "py-sonicvisualiser==0.2-9-gebe83bd"

But this leads to the following warning:

>  Downloading py_sonicvisualiser-0.2-9-gebe83bd.tar.gz
>  Running setup.py egg_info for package py-sonicvisualiser
>    /tmp/tsdiademsenv/local/lib/python2.7/site-packages/setuptools-11.0-py2.7.egg/setuptools/dist.py:293: UserWarning: The version specified ('0.2-9-gebe83bd') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>      "details." % self.metadata.version

see PEP 440: https://www.python.org/dev/peps/pep-0440/

The proper fix would be for _py_sonicvisualiser_  to follow a PEP440 compatible naming convention as 0.2.9 for example.

**Comment by DavidDoukhan** [comment]
This issue is fixed! Thanks!

**Comment by thomasfillon** [comment]
Great thank you David !

**Comment by thomasfillon** [comment]
so the proper version is 0.3 now. That's it ?

**Comment by DavidDoukhan** [comment]
yes!

**Comment by thomasfillon** [comment]
ok thanks
